version: '3.8'
services: 
    web:
        build:
            context: .
        env_file: ./.env
        command: yarn dev
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        depends_on: 
            - mysqldb
        environment: 
            DB_HOST: mysqldb
            DB_USERNAME: $DB_USERNAME
            DB_PASSWORD: $DB_PASSWORD
            DB_DATABASE: $DB_DATABASE
            APP_PORT: $APP_PORT
    mysqldb:
        image: mysql
        env_file: ./.env
        environment: 
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config:
      